replicaCount: 2

image:
  repository: aliakkas006255/backend-go
  tag: 58e9015ec497d5b093bc0450abf89d55f1b1731f
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

# NGINX ingress controller
ingressNginx:
  enabled: true
  controller:
    replicaCount: 2
    service:
      type: LoadBalancer
    metrics:
      enabled: true
    watchIngressWithoutClass: true

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: todo.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: todo-app-tls
      hosts:
        - todo.example.com

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http


autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

postgresql:
  enabled: false
  auth:
    database: postgres
    username: admin
    password: password

kafka:
  enabled: false
  replicaCount: 3
