apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster-infra
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.11.2
    chart: ingress-nginx
    helm:
      releaseName: ingress-nginx
      values: |
        controller:
          service:
            type: LoadBalancer
            loadBalancerIP: 192.168.56.150
          admissionWebhooks:
            enabled: true
          metrics:
            enabled: true
          extraArgs:
            enable-ssl-passthrough: ""
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
