apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: dev
  source:
    repoURL: https://github.com/aliakkas006/microservices-gitops-k8s.git
    targetRevision: main
    path: charts/todo
    helm:
      valueFiles:
        - values-dev.yaml
      parameters:
        - name: image.tag
          value: v1.0.0
        - name: ingress.enabled
          value: "true"
        - name: ingress.className
          value: "nginx"
  destination:
    server: https://kubernetes.default.svc
    namespace: todo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
